language: python
dist: xenial
python:
    - 2.7
    - 3.6
    - 3.7
    - 3.8-dev
    - pypy
    - pypy3
install:
    - pip install tox-travis coveralls coverage
script:
    - tox
after_success:
    - coveralls
cache:
  pip: true
